/** 公式大意：保留〔槽位〕，不要用填入後的場景例句冒充對譯 */
export const catalogueGloss = {
  "cat-1-a-01": "我一直想問懂〔領域〕的人……你是怎麼開始接觸〔主題〕的？",
  "cat-1-a-02": "我忍不住注意到你的〔物品/配件〕。它背後有什麼故事？",
  "cat-1-a-03": "所以，〔工作/學校〕之外，最近有什麼事讓你又忙又興奮？",
  "cat-1-a-04": "我正想擴充我的〔清單〕清單。這附近有什麼必試的〔清單項目〕？",
  "cat-1-a-05": "如果餘生只能選一種〔類別〕來〔動作〕，你會選什麼？",
  "cat-1-a-06": "你最近有沒有在做什麼特別有熱情的個人計畫或〔活動〕？",
  "cat-1-a-07": "我其實很新進〔領域/群體〕。有哪一件事是大家都該知道的？",
  "cat-1-a-08": "〔事件/趨勢〕我聽很多了。身為〔身份〕，你怎麼看？",
  "cat-1-a-09": "你這個〔時間段〕最精彩的是什麼？有沒有意料之外的事？",
  "cat-1-b-10": "你覺得一般人對〔主題/職業〕最大的誤解是什麼？",
  "cat-1-b-11": "如果金錢和時間都不是問題，你會怎麼做〔問題/計畫〕？",
  "cat-1-b-12": "我在〔選項A〕和〔選項B〕之間猶豫。依你的經驗，哪個效果比較好？",
  "cat-1-b-13": "面對〔棘手狀況〕時，你的黃金法則是什麼？",
  "cat-1-b-14": "我太喜歡你處理〔事件〕的方式了。你做決定時心裡在想什麼？",
  "cat-1-b-15": "1 到 10 分，你對〔產業/趨勢〕的未來有多樂觀？為什麼？",
  "cat-1-b-16": "哪一個〔名詞〕徹底改變了你看待〔領域〕的方式？",
  "cat-1-b-17": "如果你能給〔過去身份〕一個關於〔主題〕的建議，會是什麼？",
  "cat-1-b-18": "關於〔領域〕，大多數人拒絕承認的殘酷真相是什麼？",
  "cat-1-c-19": "這觀點太迷人了。是什麼讓你得出這個結論的？",
  "cat-1-c-20": "你前面提到〔關鍵字〕。能再多展開那一段嗎？",
  "cat-1-c-21": "我從沒這樣想過。那這在〔具體情境〕裡會怎麼呈現？",
  "cat-1-c-22": "聽起來像是〔對方的感受〕。有沒有一個特定瞬間觸發了它？",
  "cat-1-c-23": "這很有道理。但你怎麼把它跟〔相互衝突的事物〕平衡？",
  "cat-1-c-24": "如果是這樣，你覺得〔主體〕下一步合乎邏輯的行動是什麼？",
  "cat-1-c-25": "這視角很獨特。當你〔行動〕時，曾遇過什麼反對嗎？",
  "cat-1-c-26": "我好喜歡這個比喻！你會把同樣邏輯用在〔另一個主題〕上嗎？",
  "cat-1-c-27": "你把它說得好輕鬆，但〔任務〕最難的部分是什麼？",
  "cat-1-d-28": "有什麼是你以前對〔主題〕深信不疑，現在卻完全改觀的？",
  "cat-1-d-29": "大家好像都很愛〔熱門事物〕。我是唯一覺得它有點過譽的人嗎？你覺得呢？",
  "cat-1-d-30": "在〔領域〕裡，有哪個主流建議你其實覺得是爛建議？",
  "cat-1-d-31": "如果你能完全消除〔日常/工作〕裡一件煩人的事，會是什麼？",
  "cat-1-d-32": "你有沒有什麼古怪習慣，其實能幫你〔目標〕？",
  "cat-1-d-33": "如果我們唱一下反調，〔計畫/決策〕最大的風險是什麼？",
  "cat-1-d-34": "關於〔主題〕，你希望別人多問、但大家從不問的問題是什麼？",
  "cat-1-d-35": "如果必須為〔某段經歷〕寫個書名，會叫什麼？",
  "cat-1-d-36": "關於〔問題〕，你見過最不傳統但最有效的解法是什麼？",
  "cat-2-a-01": "這件事我想了很久，從我的立場來看，〔想法〕……",
  "cat-2-a-02": "如果我錯了請糾正我，但真正的問題似乎不是〔A〕，而是〔B〕。",
  "cat-2-a-03": "因為我的〔領域〕背景，我可能有點偏見，但我真心認為〔想法〕。",
  "cat-2-a-04": "順著你剛才說的，我注意到〔觀點〕。",
  "cat-2-a-05": "如果從〔角度〕來看，這其實是高招，因為〔原因〕。",
  "cat-2-a-06": "我以前也這樣想，但最近的經歷讓我意識到〔新觀點〕。",
  "cat-2-a-07": "你提到這個很有趣，因為依我的經驗，〔個人經驗/觀點〕。",
  "cat-2-a-08": "先不談太技術的部分，我這邊的核心結論是〔結論〕。",
  "cat-2-a-09": "我不是〔主題〕專家，但對我來說，〔直覺觀點〕。",
  "cat-2-b-10": "事情都有兩面：一方面〔優點〕，另一方面〔缺點〕。",
  "cat-2-b-11": "客觀來看，這不只是〔表面問題〕，而是〔核心議題〕的大局。",
  "cat-2-b-12": "拆開來看，有三個關鍵因素：〔因素1〕、〔因素2〕，最重要的是〔因素3〕。",
  "cat-2-b-13": "我們得考慮漣漪效應。如果我們〔行動〕，可能帶來〔連帶後果〕。",
  "cat-2-b-14": "談到〔主題〕，我的哲學很簡單：〔核心原則〕。",
  "cat-2-b-15": "依我看，〔主體〕是雙刃劍。它可以〔好處〕，也可以〔壞處〕。",
  "cat-2-b-16": "這不是「如果」的問題，而是「何時」。我們遲早會看到〔某種趨勢〕。",
  "cat-2-b-17": "對我來說，好〔事物〕的基準是它能不能〔標準〕。",
  "cat-2-b-18": "我們必須透過〔某個群體〕的視角來看，他們通常最在乎〔需求〕。",
  "cat-2-c-19": "我懂你的出發點，但我們有沒有考慮過〔另一個隱憂〕？",
  "cat-2-c-20": "這對〔情境A〕來說成立，但我好奇對〔情境B〕是否仍然成立。",
  "cat-2-c-21": "我尊重那個觀點，但我唯一的保留是〔擔憂〕。",
  "cat-2-c-22": "關於〔同意的部分〕你完全正確，但從另一個角度看，〔反面觀點〕。",
  "cat-2-c-23": "這在理論上很棒，但實務上我們可能會碰到〔實際問題〕。",
  "cat-2-c-24": "大方向我贊成，我只是對〔特定細節〕有一點不同看法。",
  "cat-2-c-25": "這絕對是一種看法，但另一種可能是〔另一種可能性〕。",
  "cat-2-c-26": "我這裡唱個反調：如果〔最壞情況〕會怎樣？",
  "cat-2-c-27": "我沒有完全被〔對方的結論〕說服，主要是因為〔原因〕。",
  "cat-2-d-28": "你一針見血。這正是我們現在需要的那種〔名詞〕。",
  "cat-2-d-29": "我再同意不過了。我們早就該〔採取行動/改變〕。",
  "cat-2-d-30": "這會改寫規則。它完全免除了〔麻煩事〕。",
  "cat-2-d-31": "我心裡毫無疑問，〔確信的事〕。",
  "cat-2-d-32": "如果有一件事我絕對確定，那就是〔觀點〕。",
  "cat-2-d-33": "這絕對是我今年看過最棒的〔事物〕。",
  "cat-2-d-34": "你把我一直講不清楚的想法，準確說出來了。",
  "cat-2-d-35": "這是〔現象〕的經典例子，它證明了〔結論〕。",
  "cat-2-d-36": "那個論點很扎實，幾乎沒有反駁餘地。",
  "cat-3-a-01": "你絕對不會相信那天我正在〔做某事〕時，發生了什麼……",
  "cat-3-a-02": "這讓我想起以前我還在〔時空背景〕時，一個又尷尬又好笑的故事……",
  "cat-3-a-03": "我有沒有跟你說過，我差點〔差點發生的驚人大事〕的那次？",
  "cat-3-a-04": "我最近陷入一種「能出錯的，全出錯了」的狀況。",
  "cat-3-a-05": "如果你想聽什麼叫〔某種特質〕，讓我跟你講〔某人/某事〕。",
  "cat-3-a-06": "我最近看到一則關於〔主題〕的怪新聞，讓我開始想……",
  "cat-3-a-07": "想像這個畫面：〔時間/天氣〕，你正在〔動作〕，突然間……",
  "cat-3-a-08": "我發誓這是真的，雖然聽起來完全像編的。",
  "cat-3-a-09": "我用很慘的代價才學到：絕對不要〔做某件蠢事〕。事情是這樣的。",
  "cat-3-b-10": "交代一下：我當時已經〔某種負面狀態〕，所以最不需要的就是〔另一件衰事〕。",
  "cat-3-b-11": "長話短說，我們人在〔某個混亂地方〕正中央，而且完全沒有〔必備物品〕。",
  "cat-3-b-12": "那一刻我腦子轉很快，心裡一直想著：「〔當時內心的OS〕」。",
  "cat-3-b-13": "不知從哪冒出來，這個〔人/物〕突然開始〔動作〕。",
  "cat-3-b-14": "我們正放鬆下來，以為最糟的過了，但當時哪知道……",
  "cat-3-b-15": "最搞笑的是〔某人〕臉上的表情，看起來就像剛〔驚嚇表情形容〕。",
  "cat-3-b-16": "彷彿還不夠，緊接著〔更扯的延伸事件〕。",
  "cat-3-b-17": "你得理解，我是那種〔個人特質〕的人，所以這對我簡直是噩夢。",
  "cat-3-b-18": "我們一邊想〔困難的目標〕，一邊還〔同時發生的阻礙〕。當時一團亂。",
  "cat-3-c-19": "就在那個精確瞬間，劇情轉厚了。〔轉折事件〕。",
  "cat-3-c-20": "正當我以為不可能再更怪，你猜又發生什麼？",
  "cat-3-c-21": "但最絕的是：〔出人意料的核心笑點/轉折〕。",
  "cat-3-c-22": "我低頭一看，驚恐地發現〔驚人發現〕。",
  "cat-3-c-23": "接著轉折點來了。突然，〔關鍵人物/事件〕改變了一切。",
  "cat-3-c-24": "那簡直像從喜劇電影搬出來。我就站在那，〔動作〕。",
  "cat-3-c-25": "出乎意料，不但沒〔預期的壞結果〕，實際發生的是〔相反的好結果〕。",
  "cat-3-c-26": "這已經無法回頭。我必須在〔選項A〕或〔選項B〕之間選。",
  "cat-3-c-27": "而那就是最後一根稻草。我再也〔動作〕不了。",
  "cat-3-d-28": "所以啦，長話短說，這就是我最後〔荒謬的最終結局〕的原因。",
  "cat-3-d-29": "故事寓意：永遠、在任何情況下，都不要〔學到的核心教訓〕。",
  "cat-3-d-30": "現在回頭看很好笑，但當時我真的以為〔當時的絕望想法〕。",
  "cat-3-d-31": "每次我們〔觸發回憶的動作〕，都還會拿這件事笑。這已變成長期笑梗。",
  "cat-3-d-32": "那時候一點都不好笑，但就像大家說的，喜劇就是悲劇加時間，對吧？",
  "cat-3-d-33": "整個災難裡唯一的銀邊，大概是〔不幸中的大幸〕。",
  "cat-3-d-34": "所以如果你哪天也〔相似的尷尬情境〕，現在你知道什麼不該做了！",
  "cat-3-d-35": "這給了我關於〔抽象概念〕很寶貴的一課，而我一點都不想改。",
  "cat-3-d-36": "那簡直是一場事故，但至少能變成好故事，對吧？有人也有〔相似經歷〕嗎？",
  "cat-4-a-01": "我甚至無法想像你當時有多〔情緒形容詞〕。換作任何人，都會〔反應〕。",
  "cat-4-a-02": "這聽起來真的〔負面形容詞〕。你會有這種感覺完全合理。",
  "cat-4-a-03": "哇，你現在一定高興瘋了！你為〔事物〕付出了那麼多心血。",
  "cat-4-a-04": "這是巨大的成功！我真心為你感到無比高興。",
  "cat-4-a-05": "如果我是你，我也會〔情緒反應〕。這真的需要時間消化。",
  "cat-4-a-06": "這太不容易了。那樣的一天之後還能〔行動〕，需要很大勇氣。",
  "cat-4-a-07": "我很遺憾你必須經歷這些。沒有人該去面對〔糟糕的情況〕。",
  "cat-4-a-08": "天啊，這聽起來像坐雲霄飛車。你還撐得住嗎？",
  "cat-4-a-09": "我在這裡都能感到你的興奮！這真的有感染力。",
  "cat-4-b-10": "所以如果我沒聽錯，壓力來源不是〔A〕，而是〔B〕？",
  "cat-4-b-11": "聽起來你左右為難：一方面〔難處A〕，另一方面〔難處B〕。",
  "cat-4-b-12": "如果我錯了請糾正我，但你真正想要的似乎只是一點〔內心需求〕。",
  "cat-4-b-13": "所以你基本上是說，目前系統是〔形容詞〕，而且把人逼到極限？",
  "cat-4-b-14": "感覺這陣子你一直獨自扛著〔某種責任〕。",
  "cat-4-b-15": "如果我總結你剛分享的，這基本上是〔現象/狀況〕的經典案例。我理解對嗎？",
  "cat-4-b-16": "你提到〔關鍵字〕好幾次。看來那部分對你最重要，對吧？",
  "cat-4-b-17": "所以對你來說，底線是只要〔條件〕，你就願意〔付出〕，對嗎？",
  "cat-4-b-18": "聽起來你不是在找〔選項A〕，你只是需要〔選項B〕。",
  "cat-4-c-19": "嘿，別把自己的努力縮小。為〔做到的成果〕給自己記上一功。",
  "cat-4-c-20": "從旁觀者來看，我一直很欽佩你〔某種優點〕。這很罕見。",
  "cat-4-c-21": "你對自己太苛刻了。看看從〔過去的時間點〕以來，你已經走了多遠。",
  "cat-4-c-22": "如果有人能從這團亂裡找到出路，那絕對是你。我看你辦到過。",
  "cat-4-c-23": "你已經用當時擁有的資訊做出最好的決定。別再回頭後悔。",
  "cat-4-c-24": "現在還沒全部想透也沒關係。沒有人要你當超級英雄。",
  "cat-4-c-25": "你的感受百分之百成立。別讓人覺得你是在過度反應。",
  "cat-4-c-26": "無論你怎麼選，我都在你這邊。你的直覺很準，相信它。",
  "cat-4-c-27": "這只是路上的顛簸，不是路的盡頭。你會反彈得更有力。",
  "cat-4-d-28": "你把這些憋很久了吧？想把剩下的也說出來嗎？",
  "cat-4-d-29": "對現在的你來說，整件事最讓你心力交瘁的是哪一段？",
  "cat-4-d-30": "我現在怎麼幫你最好？要一起想辦法，還是只要聽你說？",
  "cat-4-d-31": "今天有什麼小事，能讓你肩膀輕一點？",
  "cat-4-d-32": "關於〔事件〕，還有什麼讓你睡不著嗎？",
  "cat-4-d-33": "我知道你習慣照顧每個人，但現在誰在照顧你？",
  "cat-4-d-34": "現在不用管講得清不清楚。想到什麼就說，我聽著。",
  "cat-4-d-35": "今晚不必把整件事修好。我們先專心撐過〔時間段〕，好嗎？",
  "cat-4-d-36": "謝謝你願意信任我、跟我說這些。這對我意義很大，我都在。",
};

/**
 * 跨層關鍵語：同一說法在「風格／公式／句型」裡角色不同。
 * keywords 用來搜尋與自動配對。
 */
export const layerFamilies = [
  {
    id: "bottom-line",
    title: "bottom line",
    keywords: ["bottom line"],
    how: "風格裡的 The bottom line is，是你觀察完後自己收斂結論。公式裡的 the bottom line for you，是複述對方的底線、證明你有在聽。先用公式接住，再用風格給出你的定見。",
    together: "So the bottom line for you is that as long as the goal is clear, you’re willing to put in the extra hours, right? Fair enough. The bottom line is, we need a solution that works for everyone involved.",
    togetherZh: "所以對你來說，底線是只要目標清楚，你就願意多付出，對嗎？有道理。重點是，我們需要一個對所有相關的人都行得通的方案。",
    roles: {
      style: "你的語氣：把重點直接放到桌上。",
      catalogue: "傾聽公式：確認對方的底線，而不是搶著給結論。",
      phrase: "句型積木：用類似收束語把討論拉回核心。",
    },
  },
  {
    id: "fair-enough",
    title: "fair enough",
    keywords: ["fair enough"],
    how: "風格裡的 Fair enough 是消化對方邏輯、再決定要不要轉折。公式裡出現時，常接「但我們看實際面」。它不是投降，是先點頭再帶入你的觀察。",
    together: "Fair enough, I see where you’re coming from. That being said, let’s look at the practical side of things.",
    togetherZh: "有道理，我懂你從哪來。話雖如此，我們還是看實際面。",
    roles: {
      style: "觀察者語氣：我聽懂了，且承認你的邏輯。",
      catalogue: "不同意公式：用公平作墊，再問隱憂或實際面。",
    },
  },
  {
    id: "long-story-short",
    title: "long story short",
    keywords: ["long story short"],
    how: "風格裡用來高效收束。說故事公式裡則是鋪陳混亂現場時的潤滑劑。講故事時用公式把聽眾放進現場；收尾再用風格把話權拿回來。",
    together: "Long story short, we found ourselves in the middle of a foreign airport with absolutely no cell service. The bottom line is, we still made it.",
    togetherZh: "長話短說，我們人在國外機場正中央，完全沒有訊號。重點是，我們還是抵達了。",
    roles: {
      style: "連接詞：跳過細節、給結果。",
      catalogue: "故事公式：交代混亂現場。",
      phrase: "句型：同一條收束語，生活與工作都能用。",
    },
  },
  {
    id: "that-being-said",
    title: "that being said",
    keywords: ["that being said", "having said that"],
    how: "這是風格層的轉折器，比 but 更專業。公式層若要不同意，用 I see where you’re coming from 先接住，再用 That being said 轉入你的角度。",
    together: "I see where you’re coming from. That being said, from a logical standpoint, this is our best bet.",
    togetherZh: "我懂你的出發點。話雖如此，從邏輯上看，這是我們最好的選擇。",
    roles: {
      style: "邏輯轉折：承認前一句，再加另一個維度。",
      catalogue: "溫和不同意：先接住，再提出隱憂。",
    },
  },
  {
    id: "to-be-fair",
    title: "to be fair",
    keywords: ["to be fair"],
    how: "風格裡用來在直率意見前加公平。公式裡的高 EQ 反駁常需要這層墊句，才不會像在否定對方。",
    together: "To be fair, it’s a pretty complex system to learn in one day. I respect that view, but my only reservation is that we might be rushing.",
    togetherZh: "平心而論，這套系統要一天學會確實挺複雜。我尊重那個觀點，我唯一的保留是我們可能太趕。",
    roles: {
      style: "平衡直率：先給公道話。",
      catalogue: "表達觀點：把公平當成不同意的入場券。",
    },
  },
  {
    id: "for-what-its-worth",
    title: "for what it's worth",
    keywords: ["for what it's worth", "for what its worth"],
    how: "風格與句型都有這條。語氣較謙，適合你不想顯得強勢時丟出觀察。不要跟 The bottom line is 混用：一個是輕放，一個是拍板。",
    together: "For what it’s worth, my experience has shown that this approach works. I’m on board with the general idea, I just have a slightly different take on the timeline.",
    togetherZh: "僅供參考，依我的經驗這套作法行得通。大方向我贊成，時程上我有一點不同看法。",
    roles: {
      style: "謙虛提供觀察。",
      phrase: "句型積木：同樣的潤滑劑，可直接套進生活／工作例句。",
    },
  },
  {
    id: "correct-me",
    title: "correct me if I'm wrong",
    keywords: ["correct me if"],
    how: "句型層是委婉指出可能記錯。公式層則用來重述對方真正要的東西。前者核對事實，後者核對感受。",
    together: "Correct me if I’m wrong, but it seems like what you’re really looking for is just some breathing room.",
    togetherZh: "如果我錯了請糾正我，但你真正想要的，似乎只是一點喘息空間。",
    roles: {
      phrase: "委婉核對事實或共識。",
      catalogue: "傾聽公式：核對對方真正要的是什麼。",
    },
  },
  {
    id: "been-meaning",
    title: "I've been meaning to",
    keywords: ["been meaning to", "i’ve been meaning", "i've been meaning"],
    how: "句型層表達「想做很久但被耽擱」。公式層把同一結構變成破冰：我一直想問懂這行的人。一個講自己的待辦，一個打開別人的故事。",
    together: "I’ve been meaning to ask someone who knows about this industry… How did you get into UI design?",
    togetherZh: "我一直想問懂這行的人……你是怎麼開始接觸 UI 設計的？",
    roles: {
      phrase: "表達個人一直想做的事。",
      catalogue: "破冰公式：用「一直想問」降低搭話壓力。",
    },
  },
  {
    id: "feel-free",
    title: "feel free",
    keywords: ["feel free"],
    how: "句型層是允許對方行動。風格招牌句 Feel free to jump in 則是導覽／簡報時把發言權打開。同一禮貌，場景不同。",
    together: "Feel free to jump in if you have any thoughts. I’d appreciate it if you could share what’s not landing.",
    togetherZh: "有想法隨時插進來。如果可以的話，也跟我說哪裡還沒打到點。",
    roles: {
      style: "引導者語氣：邀請插話。",
      phrase: "句型：請對方隨時做某事。",
    },
  },
  {
    id: "torn-between",
    title: "torn between",
    keywords: ["torn between"],
    how: "句型層說出你自己的兩難。公式層則把兩難拋給對方，向他取經。一個是自我揭露，一個是深度提問。",
    together: "I’m torn between hiring an agency and doing it in-house. From your experience, which one yields better results?",
    togetherZh: "我在找外包公司和自己做之間猶豫。依你的經驗，哪個效果比較好？",
    roles: {
      phrase: "表達自己卡在兩個選項。",
      catalogue: "深度提問：請對方依經驗幫你選。",
    },
  },
  {
    id: "devils-advocate",
    title: "devil's advocate",
    keywords: ["devil’s advocate", "devil's advocate", "devils advocate"],
    how: "公式裡可當創意發問，也可當溫和唱反調。風格裡若要不同意，搭配 I’m not entirely sold yet 會比較不像在攻擊。",
    together: "I’m playing devil’s advocate here, but what happens if the vendor pulls out last minute? Actually, I’m not entirely sold on that idea yet, tell me more.",
    togetherZh: "我這裡唱個反調：如果廠商最後一刻抽腿會怎樣？其實我還沒完全被說服，多講一點。",
    roles: {
      catalogue: "提問或反駁公式：暫時站到對面。",
      style: "壓力緩衝：保留懷疑，但請對方多講。",
    },
  },
  {
    id: "put-a-pin",
    title: "put a pin in it",
    keywords: ["put a pin"],
    how: "風格招牌句與壓力緩衝都有這條：暫時擱置、不讓對話脫軌。導覽或會議超時時用它，比直接說「不要講這個」客氣。",
    together: "That’s a complex topic. Let’s put a pin in that for now and keep moving forward with the plan.",
    togetherZh: "那題很複雜。我們先釘住，計畫繼續往前。",
    roles: {
      style: "引導與壓力緩衝：先釘住，節奏不中斷。",
    },
  },
  {
    id: "from-perspective",
    title: "from a different angle",
    keywords: ["from a different angle", "from where i stand", "from my perspective", "another angle"],
    how: "風格強調「角度不同」而不是「你錯了」。公式層的立體鋪陳、高 EQ 反駁也走同一條路。不同意時先換鏡頭，再講內容。",
    together: "I appreciate that perspective, but I am looking at it from a different angle. You’re absolutely right about the design, but looking at it from another angle, it’s not very user-friendly.",
    togetherZh: "我感謝這個視角，但我從另一個角度看。設計你完全正確，但換個鏡頭看，它其實不太好用。",
    roles: {
      style: "觀察者語氣：換一個拍攝角度。",
      catalogue: "表達觀點：用另一個鏡頭講反面。",
      phrase: "句型：From my perspective… 直接亮出立場。",
    },
  },
  {
    id: "actually",
    title: "actually",
    keywords: ["i'm actually", "i’m actually"],
    titleStart: ["actually"],
    how: "風格裡用來修正誤解或講得更精確，不是反駁對方不誠實。公式破冰也有 I’m actually quite new to…，那是自我定位，不是轉折。",
    together: "I’m actually quite new to this industry. Actually, to be more precise, I just want to understand how you got into it.",
    togetherZh: "我其實很新進這一行。其實，更精確地說，我只是想搞懂你是怎麼進這行的。",
    roles: {
      style: "發語詞：提出更精確的觀察。",
      catalogue: "破冰：承認自己是新人，降低對立。",
    },
  },
  {
    id: "honestly",
    title: "honestly",
    keywords: ["honestly,", "to be honest", "to tell you the truth"],
    titleStart: ["honestly"],
    how: "風格的 Honestly 是「我要講重點了」。句型的 To tell you the truth / To be honest with you 是坦白。都不要用成質疑對方說謊。",
    together: "Honestly, I think we’re overthinking this part. To be honest with you, our team doesn’t have the bandwidth this week.",
    togetherZh: "老實說，我覺得這一段我們想太多了。坦白跟你說，我們團隊這週沒有餘裕。",
    roles: {
      style: "直率開場：進入真心話。",
      phrase: "句型：坦白講現況。",
    },
  },
  {
    id: "in-any-case",
    title: "in any case / at the end of the day",
    keywords: ["in any case", "at the end of the day"],
    how: "兩者都是收束。In any case 把混亂對話拉回行動；At the end of the day 給最終價值判斷。可接在 The bottom line is 之後，但不要三句連發。",
    together: "In any case, let’s keep moving forward. At the end of the day, the exhibition has to be easy for the public.",
    togetherZh: "總之，我們繼續往前。歸根究底，展覽必須讓大眾好走、好懂。",
    roles: {
      style: "In any case：不管剛才多亂，先聚焦。",
      phrase: "At the end of the day：歸根究底最在乎什麼。",
    },
  },
  {
    id: "moving-on",
    title: "moving on / on that note",
    keywords: ["moving on", "on that note"],
    how: "Moving on 是硬切主題，適合導覽下一站。On that note 是順著剛提到的點往下。會議超時用前者；想保持連貫用後者。",
    together: "On that note, does anyone need a quick break? Moving on to the next hall, let’s talk about how the system works.",
    togetherZh: "既然提到這點，有人需要喘一口氣嗎？接著下一個展廳，我們來看這套系統怎麼運作。",
    roles: {
      style: "節奏控制：切主題或順勢往下。",
    },
  },
];
