/** 風格短譯：卡片標題下的中文，不再用分類名稱冒充對譯 */
export const styleTitleZh = {
  "style-s1-01": "其實／更精確地說",
  "style-s1-02": "基本上／簡單來說",
  "style-s1-03": "我的意思是（補充或軟化）",
  "style-s1-04": "你知道的（把對方拉進同一套邏輯）",
  "style-s1-05": "有道理；我懂你的邏輯",
  "style-s1-06": "對……（停頓、消化）",
  "style-s1-07": "老實說；我要講重點了",
  "style-s1-08": "務實來看",
  "style-s1-09": "只是／有點像（軟化直率）",
  "style-s2-01": "重點是；底線是",
  "style-s2-02": "問題在於；關鍵是",
  "style-s2-03": "話雖如此（轉折）",
  "style-s2-04": "不過話說回來（較柔的轉折）",
  "style-s2-05": "接著談到；我們往下",
  "style-s2-06": "既然提到這點，順便說",
  "style-s2-07": "平心而論；說句公道話",
  "style-s2-08": "僅供參考；不管有沒有用",
  "style-s2-09": "長話短說",
  "style-s2-10": "總之；不管怎樣",
  "style-s3-01": "用鳥瞰角度看整體",
  "style-s3-02": "心態／觀看的框架",
  "style-s3-03": "在兩者之間找那個剛好的點",
  "style-s3-04": "先拉遠，看大局",
  "style-s3-05": "取決於你從哪個角度看",
  "style-s3-06": "這套邏輯我這邊是通的",
  "style-s3-07": "先拆成小塊",
  "style-s3-08": "我喜歡流程乾淨、有效率",
  "style-s3-09": "這件事有清楚的先後順序",
  "style-s3-10": "我們要先校準彼此的期待",
  "style-s3-11": "先看它怎麼長出來",
  "style-s3-12": "這需要一點培育",
  "style-s3-13": "我們還在試點階段",
  "style-s3-14": "事情是分階段發生的",
  "style-s3-15": "找根因，不要只治表面",
  "style-s3-16": "接下來怎麼走？",
  "style-s3-17": "我先感受這裡的氣氛",
  "style-s3-18": "把這股動能延續下去",
  "style-s3-19": "這部分交給你決定",
  "style-s3-20": "待會見（隨性道別）",
  "style-s3-21": "先把空氣澄清一下",
  "style-s3-22": "有想法隨時插話",
  "style-s3-23": "我想確認有打到你要的點",
  "style-s3-24": "這題先釘住，稍後再談",
  "style-s3-25": "我帶你把整個故事走一遍",
  "style-s4-01": "讓我先把細節消化一下",
  "style-s4-02": "我正在腦中跑過一遍邏輯",
  "style-s4-03": "給我一點時間，我想講得更精準",
  "style-s4-04": "我在腦中畫下一步的地圖",
  "style-s4-05": "讓我對一下自己的方向",
  "style-s4-06": "這個細節我想先核實再給確定答案",
  "style-s4-07": "我手上沒有精確數據，但我可以去查",
  "style-s4-08": "這超出我目前的焦點，但我知道的是……",
  "style-s4-09": "這題我還在觀察階段",
  "style-s4-10": "我稍後回你，把全貌補齊",
  "style-s4-11": "為了時間，我們先抓核心",
  "style-s4-12": "我們有點陷入細節了，先拉回來",
  "style-s4-13": "這是另一場對話，但謝謝你的意見",
  "style-s4-14": "先釘住這點，繼續往前",
  "style-s4-15": "我想確認我們還在進度上",
  "style-s4-16": "我懂你的點，但我的觀察不太一樣",
  "style-s4-17": "我感謝這個視角，但我從另一個角度看",
  "style-s4-18": "有道理，但我們看實際面",
  "style-s4-19": "我還沒完全被說服，多講一點",
  "style-s4-20": "那是一種看法，這裡還有另一種可能",
  "style-s4-21": "那我不打擾你了（優雅離開）",
  "style-s4-22": "我今天還有幾件事要劃掉",
  "style-s4-23": "等雙方都有時間再續",
  "style-s4-24": "我先離開一下，聊得很愉快",
  "style-s4-25": "有進展隨時讓我知道",
};

/** [英文例句, 中文對譯] */
export const styleExampleZh = [
  ["Actually, the process is a bit more streamlined than it looks.", "其實，這個流程比看起來更精簡。"],
  ["Actually, if we look at the data from a different angle, it makes more sense.", "其實，如果我們換個角度看這些資料，會合理得多。"],
  ["Actually, I was thinking we could try a different approach this time.", "其實，我在想這次我們可以試一條不同的路。"],
  ["Actually, to be more precise, the focus should be on the final output.", "其實，更精確地說，重點應該放在最終產出。"],
  ["Actually, that’s a common misconception, but here’s how it really works.", "其實，那是個常見誤解，真正運作的方式是這樣。"],
  ["Basically, it all boils down to two main factors.", "基本上，這一切可以收斂成兩個主要因素。"],
  ["Basically, the goal here is to keep things as simple as possible.", "基本上，這裡的目標就是盡量保持簡單。"],
  ["Basically, what I’m trying to say is that we need to prioritize efficiency.", "基本上，我想說的是我們得把效率放在前面。"],
  ["Basically, if you follow this logic, the rest of the steps fall into place.", "基本上，你只要跟著這條邏輯走，後面的步驟會自己到位。"],
  ["Basically, we’re just looking for the most effective way to get this done.", "基本上，我們只是在找把這件事做完最有效的方法。"],
  ["I mean, I don't want to overcomplicate things for you.", "我的意思是，我不想把事情弄得對你太複雜。"],
  ["I mean, it’s just a suggestion, but it might save us some time.", "我的意思是，這只是建議，但可能幫我們省一點時間。"],
  ["I mean, the whole idea is to make the experience better for everyone.", "我的意思是，整件事就是想讓每個人的體驗更好。"],
  ["I mean, let’s be real, we all want the best possible result.", "我的意思是，說實話，我們都想要最好的結果。"],
  ["I mean, I’m just looking at it from a practical standpoint.", "我的意思是，我只是從務實的角度看。"],
  ["You know, it’s one of those things where you just have to see it to get it.", "你知道的，這種事得親眼看到才會懂。"],
  ["You know, like how we usually handle these kinds of situations.", "你知道的，就像我們平常處理這類狀況的方式。"],
  ["You know, I want to make sure you’re comfortable with this timeline.", "你知道的，我想確認你對這個時程是安心的。"],
  ["You know, it’s all about finding that sweet spot between quality and speed.", "你知道的，重點就是在品質和速度之間找到那個剛好的點。"],
  ["You know, I’ve noticed that people really appreciate the details here.", "你知道的，我有注意到大家其實很在意這裡的細節。"],
  ["Fair enough, I see where you’re coming from with that point.", "有道理，我懂你這個點是從哪來的。"],
  ["Fair enough, let’s take that into consideration as we move forward.", "有道理，我們往下走時把這點納進去。"],
  ["Fair enough, that’s a valid concern to bring up.", "有道理，這確實是值得提出來的顧慮。"],
  ["Fair enough, but let’s also look at the potential downsides.", "有道理，但我們也看看可能的壞處。"],
  ["Fair enough, I can definitely work with that.", "有道理，這個我可以配合。"],
  ["Right... (停頓) So, if we take that path, what’s our next move?", "對……（停頓）那如果走這條路，下一步是什麼？"],
  ["Right... (停頓) I see the logic there, but let’s double-check the details.", "對……（停頓）我看到裡面的邏輯，但細節我們再核一次。"],
  ["Right... (停頓) That changes things a bit, doesn’t it?", "對……（停頓）這樣事情就不太一樣了，對吧？"],
  ["Right... (停頓) Let’s see how we can integrate that into the plan.", "對……（停頓）看看我們怎麼把它嵌進計畫裡。"],
  ["Right... (停頓) I’m just thinking about how that affects the overall flow.", "對……（停頓）我在想這會怎麼影響整體節奏。"],
  ["Honestly, I think we’re overthinking this part.", "老實說，我覺得這一段我們想太多了。"],
  ["Honestly, the simplest solution is usually the best one.", "老實說，最簡單的方案通常就是最好的。"],
  ["Honestly, I’d rather be upfront about the challenges we’re facing.", "老實說，我寧願把我們正面臨的挑戰直接講清楚。"],
  ["Honestly, it’s not as complicated as it sounds.", "老實說，這沒有聽起來那麼複雜。"],
  ["Honestly, I’m just happy to be part of the conversation.", "老實說，我很開心能參與這場對話。"],
  ["Realistically, we have to look at what’s possible within this timeframe.", "務實來看，我們得看這個時程內真正做得到什麼。"],
  ["Realistically, this is the most efficient way to handle the situation.", "務實來看，這是處理這個狀況最有效率的方式。"],
  ["Realistically, we should expect a few bumps along the road.", "務實來看，路上本來就會有幾個顛簸。"],
  ["Realistically, I don’t think we need to worry about that just yet.", "務實來看，我覺得現在還不必擔心那個。"],
  ["Realistically, it’s all about managing expectations from the start.", "務實來看，一開始就把期待管理好才是重點。"],
  ["I’m just trying to get a better sense of the big picture.", "我只是想把大局再看清楚一點。"],
  ["It’s just that I want to make sure we don’t miss any small details.", "只是我想確認我們沒漏掉任何小細節。"],
  ["I was just wondering if you had any thoughts on this.", "我只是好奇你對這件事有沒有想法。"],
  ["It’s like, we’re almost there, we just need one final push.", "有點像是，我們就快到了，只差最後一推。"],
  ["It’s kind of like how a camera focus works, you know?", "有點像相機對焦的方式，你懂嗎？"],
  ["The bottom line is, we need a solution that works for everyone involved.", "重點是，我們需要一個對所有相關的人都行得通的方案。"],
  ["The bottom line is, if the timing isn't right, the quality will suffer.", "重點是，時機不對，品質就會受傷。"],
  ["The bottom line is, I'm looking for the most efficient way to capture this shot.", "重點是，我在找捕捉這個鏡頭最有效率的方法。"],
  ["The bottom line is, we're here to make sure the experience is seamless.", "重點是，我們在這裡就是為了讓體驗是順的。"],
  ["The bottom line is, simplicity usually beats complexity in these cases.", "重點是，這種情況簡單通常贏過複雜。"],
  ["The thing is, we have to consider the lighting before we start the tour.", "問題是，開始導覽前我們得先考慮光線。"],
  ["The thing is, I've seen this happen before, and here’s how we fixed it.", "問題是，這事我見過，而我們當時是這樣修的。"],
  ["The thing is, I want to make sure we're all on the same page first.", "問題是，我先想確認大家認知一致。"],
  ["The thing is, realistically, we only have about twenty minutes left.", "問題是，務實來說我們大概只剩二十分鐘。"],
  ["The thing is, it’s not just about the technical side, it’s about the feeling.", "問題是，這不只是技術面，還有感覺。"],
  ["That being said, I still think there’s a lot of potential in your idea.", "話雖如此，我還是覺得你的想法很有潛力。"],
  ["That being said, we should probably keep an eye on the budget.", "話雖如此，預算我們大概還是得盯著。"],
  ["That being said, from a logical standpoint, this is our best bet.", "話雖如此，從邏輯上看，這是我們最好的選擇。"],
  ["That being said, I’m open to suggestions if you have a better way.", "話雖如此，如果你有更好的作法，我很開放。"],
  ["That being said, let’s not lose sight of the original goal.", "話雖如此，別把原本的目標看丟了。"],
  ["Having said that, I totally understand why you’d feel that way.", "不過話說回來，我完全理解你為什麼會這樣覺得。"],
  ["Having said that, maybe we can find a middle ground that works.", "不過話說回來，也許我們能找到一個都行的中間點。"],
  ["Having said that, it’s worth taking a second look at the details.", "不過話說回來，細節值得再看一眼。"],
  ["Having said that, I’m confident we can handle any issues that come up.", "不過話說回來，我有信心能處理冒出來的問題。"],
  ["Having said that, let’s see what happens if we change the focus a bit.", "不過話說回來，看看我們把焦點稍微挪一下會怎樣。"],
  ["Moving on to the next part, let's talk about the history of this place.", "接著下一段，我們來談這個地方的歷史。"],
  ["Moving on to the logistics, here’s how the rest of the day looks.", "接著談後勤，今天剩下的行程是這樣。"],
  ["Moving on to the technical specs, I’ll keep it as simple as possible.", "接著技術規格，我會盡量講簡單。"],
  ["Moving on to your questions, I’d love to hear what’s on your mind.", "接著你們的問題，我很想聽你們在想什麼。"],
  ["Moving on, let’s take a look at the results from the last session.", "接著，我們看一下上次的結果。"],
  ["On that note, I should probably mention the upcoming exhibition.", "既然提到這點，我應該提一下即將到來的展覽。"],
  ["On that note, does anyone need a quick break before we continue?", "既然提到這點，繼續前有人需要喘一口氣嗎？"],
  ["On that note, it reminds me of a similar project I worked on last year.", "既然提到這點，這讓我想起去年做過的類似專案。"],
  ["On that note, let’s make sure we have all the equipment ready.", "既然提到這點，我們確認一下器材都準備好了。"],
  ["On that note, I’ll let you be the judge of which direction we take.", "既然提到這點，方向交給你來判斷。"],
  ["To be fair, it’s a pretty complex system to learn in one day.", "平心而論，這套系統要一天學會確實挺複雜。"],
  ["To be fair, we’ve all been working really hard on this lately.", "平心而論，最近大家在這件事上都非常拚。"],
  ["To be fair, the original plan was a bit too ambitious for the timeframe.", "平心而論，原本的計畫以這個時程來說有點太雄心。"],
  ["To be fair, I think everyone did their best given the circumstances.", "平心而論，以當時條件來看，我覺得每個人都盡力了。"],
  ["To be fair, it’s hard to get the perfect shot without the right gear.", "平心而論，沒有對的器材，很難拍到完美的那一張。"],
  ["For what it's worth, I think you handled that situation perfectly.", "僅供參考，我覺得那件事你處理得很好。"],
  ["For what it's worth, my experience has shown that this approach works.", "僅供參考，依我的經驗，這套作法是行得通的。"],
  ["For what it's worth, I’m really impressed with how this turned out.", "僅供參考，成品變成這樣我真的印象很深。"],
  ["For what it's worth, I’d be happy to help you with the editing later.", "僅供參考，待會剪輯我很樂意幫忙。"],
  ["For what it's worth, I don't think you need to worry too much about it.", "僅供參考，我覺得這件事你不必太擔心。"],
  ["Long story short, we decided to go with the second option.", "長話短說，我們決定走第二個方案。"],
  ["Long story short, it was a great learning experience for the whole team.", "長話短說，對整個團隊來說是一次很好的學習。"],
  ["Long story short, the project is back on track and looking good.", "長話短說，專案回到軌道上了，看起來不錯。"],
  ["Long story short, I ended up getting the certification after all.", "長話短說，我最後還是拿到證照了。"],
  ["Long story short, everything worked out in the end.", "長話短說，最後一切都過得去。"],
  ["In any case, we should probably head back to the main hall now.", "總之，我們大概該回主展廳了。"],
  ["In any case, I’ll make sure to send you the updated files tonight.", "總之，今晚我會把更新檔寄給你。"],
  ["In any case, the most important thing is that we stay focused.", "總之，最重要的是我們保持專注。"],
  ["In any case, I’m just glad we could clear that up together.", "總之，我很高興我們能一起把這件事講清楚。"],
  ["In any case, let’s keep moving forward and see what happens next.", "總之，我們繼續往前，看下一步會怎樣。"],
  ["Before we dive into the technicalities, let’s look at this from a bird’s eye view to see the main objective.", "在鑽進技術細節前，我們先用鳥瞰角度看主要目標。"],
  ["When you’re exploring this exhibition, it’s all about the frame of mind you bring to each piece.", "你逛這個展覽時，重點是你帶去每一件作品的心態框架。"],
  ["I’m looking for that sweet spot between keeping it professional and staying casual.", "我在找專業和隨性之間那個剛好的點。"],
  ["Let’s zoom out for a second. The goal here isn’t just speed, it’s also about the long-term impact.", "我們先拉遠一秒。這裡的目標不只是速度，還有長期影響。"],
  ["Whether this is a good investment or not, well, it depends on the angle you’re taking.", "這算不算好投資，得看你從哪個角度看。"],
  ["I’ve reviewed the plan, and the logic checks out on my end. Let’s move forward.", "計畫我看過了，邏輯我這邊是通的。我們往下走。"],
  ["This project seems massive, but let’s break this down into smaller, manageable pieces first.", "這專案看起來很大，但我們先拆成比較好處理的小塊。"],
  ["To be honest, I like things to be streamlined and efficient, so let’s get straight to the point.", "老實說，我喜歡事情精簡有效率，所以我們直接講重點。"],
  ["Don’t worry about the complexity; there’s a clear sequence to how this system operates.", "別被複雜嚇到；這套系統怎麼運作，其實有清楚的順序。"],
  ["I think we just need to calibrate our expectations for the trip so everyone stays happy.", "我覺得行程的期待我們只要先校準，大家才都會開心。"],
  ["It’s a new project, so let’s just see how this develops over time without rushing it.", "這是新專案，我們先看它怎麼長，不必催。"],
  ["The team dynamic is good, but it needs a bit of nurturing to really get it right.", "團隊氛圍是好的，但還需要一點培育，才會真正到位。"],
  ["Regarding our weekend plans, let’s say we’re in the pilot phase. I’m still checking the weather.", "週末計畫就說我們還在試點階段。我還在看天氣。"],
  ["Don’t feel overwhelmed. Everything happens in stages, and we’re currently in the best one.", "別被壓垮。事情是分階段發生的，而我們正處在最好的那一段。"],
  ["To fix this issue for good, we need to find the root cause, not just address the symptoms.", "要把這問題徹底修好，得找根因，不能只處理表面症狀。"],
  ["That was a great lunch. What’s the move for the rest of the day?", "午餐很棒。接下來今天還要幹嘛？"],
  ["Don’t mind me, I’m just vibing with the atmosphere here. It’s a great spot.", "別管我，我先感受這裡的氣氛。這地方很好。"],
  ["We’ve seen two great houses already. Let’s keep the momentum going and see the last one.", "我們已經看了兩間很棒的房子。把這股動能延續下去，看最後一間。"],
  ["You know the area better than I do, so I’ll leave the restaurant choice to your discretion.", "這區你比我熟，餐廳就交給你決定。"],
  ["I have to run to a meeting now. Catch you on the flip side!", "我得趕去開會了。待會見！"],
  ["Just to clear the air, the maintenance won’t affect your visit today.", "先澄清一下：維修不會影響你今天的參觀。"],
  ["I’ve been talking for a while. Feel free to jump in if you have any thoughts or questions.", "我講了一段時間了。有想法或問題隨時插進來。"],
  ["In terms of this tour, I want to make sure I’m hitting the mark for you. Is this what you expected?", "就這次導覽來說，我想確認有打到你要的點。這是你預期的嗎？"],
  ["That’s a complex topic. Let’s put a pin in that for now and come back to it after the tour.", "那題很複雜。我們先釘住，導覽結束再回來。"],
  ["Welcome to the facility. I’m here to walk you through the whole story of how we generate power.", "歡迎來到園區。我會帶你把我們怎麼發電的整個故事走一遍。"],
  ["That is a complex question. Let me just process the details on that for a second before I give you an answer.", "這題不簡單。讓我先把細節消化一下，再給你答案。"],
  ["Right... I am just running the logic through my head to make sure I missed nothing in the sequence.", "對……我正在腦中把邏輯跑一遍，確認順序裡沒漏。"],
  ["That is a great point. Give me a moment to find the most precise way to phrase this for you.", "這點很好。給我一下，我想用最精準的方式跟你講。"],
  ["I hear you. I am just mental-mapping the next steps here to see how they align with our goal.", "我聽到了。我在腦中畫下一步，看它們跟目標怎麼對齊。"],
  ["That is a new perspective. Let me double-check my internal compass on this one for a moment.", "這是個新角度。讓我對一下自己的方向再回你。"],
  ["Regarding the technical specs of the drone, that is a specific detail I would like to verify before giving you a definitive answer.", "關於無人機的技術規格，這個細節我想先核實，再給你確定的答案。"],
  ["Honestly, I do not have the exact data on me right now, but I can certainly find out and get back to you.", "老實說，我手上現在沒有精確數據，但我可以去查再回你。"],
  ["To be fair, the real estate laws are tricky. That is outside my current focus, but here is what I do know about the local market.", "平心而論，房地產法規很刁。那超出我目前的焦點，但我對在地市場知道的是這些。"],
  ["People are talking about the new tech, but I am still in the observation phase regarding that particular topic.", "大家都在聊那個新科技，但那題我還在觀察階段。"],
  ["I want to be accurate, so let me get back to you on that so I can give you the full picture later tonight.", "我想講準，所以這題我稍後回你，今晚把全貌補齊。"],
  ["I see where this is going, but in the interest of time, let us focus on the core issue first.", "我知道這會往哪走，但為了時間，我們先抓核心問題。"],
  ["The technical discussion is great, but I think we are getting a bit into the weeds here. Let us pull back to the main goal.", "技術討論很好，但我覺得我們有點陷入細節了。先拉回主目標。"],
  ["That is a conversation for another time, but I appreciate the input. For now, let’s stick to the tour.", "那是另一場對話，但謝謝你的意見。現在我們先把導覽走完。"],
  ["That is an interesting side note. Let us put a pin in that and keep moving forward with the plan.", "這是個有意思的支線。我們先釘住，計畫繼續往前。"],
  ["Basically, I want to make sure we are staying on track with our schedule, so let us move to the next hall.", "基本上，我想確認我們還在進度上，所以我們去下一個展廳。"],
  ["I see your point, though my observation suggests something slightly different regarding the engine maintenance.", "我懂你的點，不過就引擎維護來說，我的觀察有一點不一樣。"],
  ["I appreciate that perspective, but I am looking at it from a different angle, especially considering the long-term costs.", "我感謝這個視角，但我從另一個角度看，尤其是長期成本。"],
  ["Fair enough, but let us look at the practical side of things. Can we actually pull this off by Friday?", "有道理，但我們看實際面。週五前我們真的做得到嗎？"],
  ["Actually, I am not entirely sold on that idea yet, tell me more about how you plan to execute it.", "其實，我還沒完全被這個想法說服，多講一點你打算怎麼執行。"],
  ["That is one way to look at it, but here is another possibility that might be more efficient for us.", "那是一種看法，但這裡還有另一種可能，對我們也許更有效率。"],
  ["It was great catching up, but I will let you get back to what you were doing. See you around!", "敘舊很開心，那我不打擾你了。再見！"],
  ["I would love to chat more, but I have a few more things to check off my list today. Let’s talk soon.", "我很想再聊，但我今天還有幾件事要劃掉。我們很快再談。"],
  ["This was a solid discussion. Let us pick this up again when we both have more time next week.", "這場討論很扎實。下週雙方都比較有時間時再續。"],
  ["I am going to make a quick move, but it was a pleasure talking to you about the real estate exam.", "我先離開一下，跟你聊房仲考試很愉快。"],
  ["Good luck with the project. Keep me posted on how that develops!", "專案加油。有進展隨時讓我知道！"],
];
