/** GRE 高頻 800：詞表先固定，避免重複或缺漏 */
export const GRE_WORDS = [
  // 1–100
  "abandon","abate","abdicate","aberrant","abeyance","abhor","abject","abjure","abrasive","abridge",
  "abscond","absolve","abstemious","abstruse","accolade","acerbic","acme","acquiesce","acrid","acrimonious",
  "adroit","adulation","adulterate","adventitious","aesthetic","affable","affinity","affluent","aggrandize","aggregate",
  "alacrity","alleviate","alloy","allude","altruism","amalgamate","ambiguous","ambivalence","ameliorate","amenable",
  "amenity","amiable","amorphous","anachronism","analogous","anarchy","anecdotal","anomaly","antagonism","antediluvian",
  "antipathy","antithetical","apathy","apocryphal","appease","apprise","approbation","appropriate","arbitrary","arcane",
  "archaic","arduous","arid","artless","ascetic","ascribe","asperity","assail","assiduous","assuage",
  "astringent","astute","atone","attenuate","audacious","austere","autonomous","avarice","aver","avid",
  "avow","banal","bane","belie","belittle","bellicose","belligerent","benefactor","benevolent","benign",
  "bequeath","berate","bewilder","blight","bolster","bombastic","boorish","bourgeois","braggart","brazen",
  // 101–200
  "brevity","brook","bucolic","burgeon","burnish","buttress","byzantine","cacophony","cajole","callous",
  "calumny","candor","canon","cantankerous","capricious","captious","castigate","catalyst","caustic","censure",
  "chagrin","charlatan","chary","chicanery","choleric","circuitous","circumscribe","circumspect","circumvent","clairvoyant",
  "clamor","clandestine","clemency","coalesce","coax","coerce","cogent","cognizant","commensurate","compelling",
  "complacent","complaisant","complementary","compliant","complicit","conciliatory","concomitant","condone","confound","congenial",
  "conjecture","connoisseur","consecrate","consensus","conspicuous","consternation","constraint","contend","contentious","contingent",
  "contrite","contrived","conundrum","conventional","converge","convivial","convoluted","copious","corroborate","cosmopolitan",
  "countenance","coup","covert","covet","cower","craven","credulous","criterion","cryptic","culminate",
  "culpable","cumbersome","cupidity","cursory","cynical","daunt","dearth","debacle","debilitate","decorum",
  "default","deference","defunct","deleterious","delineate","demeanor","denigrate","denizen","denounce","deplete",
  // 201–300
  "deplore","depose","depravity","deprecate","deride","derivative","desiccate","despondent","despot","desultory",
  "detached","deterrent","diatribe","dichotomy","didactic","diffident","diffuse","digress","dilatory","dilettante",
  "diligent","diminution","dirge","disabuse","discern","disconcert","discordant","discredit","discrepancy","discrete",
  "discretion","disdain","disingenuous","disinterested","disjointed","disparage","disparate","dispassionate","dispatch","dispel",
  "disperse","dissemble","disseminate","dissent","dissolution","dissonance","distend","distill","diverge","divest",
  "divulge","doctrine","dogmatic","dormant","dour","dubious","dupe","duplicity","ebullient","eclectic",
  "edict","edify","efface","effervescent","efficacious","efficacy","effrontery","egregious","elegy","elicit",
  "eloquent","elucidate","elude","emaciated","embellish","embezzle","embody","embryonic","empirical","emulate",
  "encomium","endemic","endorse","enervate","engender","enhance","enigma","enmity","ennui","enumerate",
  "ephemeral","epicure","epigram","epitome","equanimity","equitable","equivocal","equivocate","eradicate","erratic",
  // 301–400
  "erudite","eschew","esoteric","estimable","estrange","eulogy","euphemism","euphoria","evade","evanescent",
  "exacerbate","exacting","exalt","exasperate","excerpt","exculpate","execrable","exemplary","exhaustive","exhort",
  "exigency","exonerate","expedient","expedite","explicit","exploit","expound","extant","extemporaneous","extol",
  "extraneous","extrapolate","extricate","exuberant","fabricate","facetious","facilitate","faction","fallacious","fallow",
  "fanatical","fastidious","fathom","fatuous","fawn","feasible","feckless","fecund","feign","felicitous",
  "feral","fervent","fervid","fervor","fickle","fidelity","flag","flagrant","flamboyant","fledgling",
  "flippant","flout","fluke","foible","foment","forbear","forestall","formidable","fortuitous","foster",
  "founder","fractious","fraught","frenetic","frugal","fulminate","fulsome","furtive","futile","gaffe",
  "gainsay","galvanize","garish","garrulous","gaudy","germane","glib","glut","goad","gouge",
  "grandiloquent","grandiose","gratuitous","gregarious","grovel","guile","guileless","gullible","hackneyed","hallow",
  // 401–500
  "hamper","harangue","harbinger","hardy","haughty","hedonism","hegemony","heresy","hermetic","heterogeneous",
  "hiatus","hierarchy","hindrance","homage","homogeneous","hone","husband","hyperbole","hypocritical","iconoclast",
  "ideology","idiosyncrasy","idolatry","idyllic","ignoble","ignominious","illicit","illustrious","imbibe","imbue",
  "imminent","immutable","impair","impartial","impasse","impassive","impede","impending","impermeable","imperturbable",
  "impervious","impetuous","implacable","implement","implicit","implode","importune","impostor","impoverished","impregnable",
  "improvident","improvise","imprudent","impudent","impugn","inadvertent","inane","inaugurate","incendiary","incense",
  "inception","incessant","inchoate","incidental","incisive","incite","inclination","incongruous","inconsequential","incorporate",
  "incorrigible","incredulous","increment","incriminate","incumbent","indefatigable","indigenous","indigent","indolent","indomitable",
  "induce","ineffable","inept","inert","inevitable","inexorable","infamous","inference","infuse","ingenious",
  "ingenuous","ingrained","inherent","inhibit","inimical","iniquity","innate","innocuous","innovative","innuendo",
  // 501–600
  "inordinate","insatiable","insensible","insidious","insightful","insinuate","insipid","insolent","insular","insurgent",
  "intangible","integral","integrity","intemperate","intercede","interdict","interject","intimate","intimidate","intractable",
  "intransigent","intrepid","intricate","intrinsic","introspective","inundate","inure","invective","inveterate","invidious",
  "invigorate","irascible","irate","ironic","irresolute","itinerant","itinerary","jaded","jargon","jaundiced",
  "jejune","jeopardize","jocular","judicious","juxtapose","kindle","kinetic","kudos","laconic","lament",
  "lampoon","languid","larceny","lassitude","latent","laud","lavish","lethargic","levity","liability",
  "libertine","licentious","lionize","listless","lithe","livid","loathe","lofty","loquacious","lucid",
  "lucrative","ludicrous","lugubrious","luminous","lurid","machination","maelstrom","magnanimous","malevolent","malfeasance",
  "malice","malign","malinger","malleable","mandate","manifest","mar","martinet","maudlin","maverick",
  "maxim","meager","mediate","mediocre","melancholy","mellifluous","mercenary","mercurial","meretricious","mesmerize",
  // 601–700
  "metamorphosis","meticulous","mettle","milieu","minuscule","misanthrope","misconstrue","miserly","misnomer","mitigate",
  "mnemonic","modulate","mollify","momentous","monastic","monotonous","moratorium","morbid","moribund","morose",
  "mundane","munificent","mutable","myopic","myriad","nadir","naive","nascent","nebulous","nefarious",
  "negate","negligent","nemesis","neophyte","nettle","noisome","nomadic","nonchalant","nondescript","nonplussed",
  "nostalgia","notorious","novel","novice","noxious","nuance","nurture","obdurate","obfuscate","obliterate",
  "oblivious","obloquy","obscure","obsequious","obsolete","obstinate","obstreperous","obtuse","obviate","occlude",
  "odious","officious","ominous","omnipotent","onerous","opaque","opprobrium","opulent","ornate","orthodox",
  "oscillate","ostensible","ostentatious","ostracize","oust","outstrip","overbearing","overt","overwrought","pacify",
  "palatable","palatial","palliate","pallid","palpable","paltry","panacea","panache","pandemic","pander",
  "panegyric","paradigm","paradox","paragon","paramount","pariah","parody","parochial","parsimonious","partisan",
  // 701–800
  "pastiche","pathological","paucity","peccadillo","pedant","pedestrian","pejorative","pellucid","penchant","penitent",
  "pensive","penury","peremptory","perennial","perfidious","perfunctory","peripheral","permeable","pernicious","perpetuate",
  "perspicacious","pertinent","perturb","pervasive","petulant","philanthropic","philistine","phlegmatic","piety","pithy",
  "pittance","placate","placid","plagiarism","platitude","plausible","plethora","pliable","plight","plummet",
  "poignant","polarize","polemic","ponderous","porous","portent","pragmatic","prattle","precarious","precedent",
  "precept","precipitate","precipitous","preclude","precocious","precursor","predilection","preeminent","preempt","presage",
  "prescient","presumptuous","pretentious","prevaricate","primordial","pristine","privation","probity","proclivity","procrastinate",
  "prodigal","prodigious","profane","profligate","profound","profuse","progeny","proliferate","prolific","prominent",
  "promulgate","propensity","prophetic","propitious","proponent","prosaic","proscribe","prosperous","protean","provincial",
  "provisional","prudent","pungent","punitive","purported","quagmire","qualified","quandary","quash","querulous",
];

if (GRE_WORDS.length !== 800) {
  console.error("count", GRE_WORDS.length);
}
const dup = GRE_WORDS.filter((w, i) => GRE_WORDS.indexOf(w) !== i);
if (dup.length) console.error("dups", [...new Set(dup)]);
